Projekt Lab 11 - 12/Models/Entities/DiamondMine.cs
namespace Projekt_Lab_11___12.Models.Entities
{
    public class DiamondMine : Mine
    {
        public DiamondMine() {
            Name = "Kopalnia Diamentów";
            MineResourceType = ResourceType.Diamond;
        }
    }
}

Projekt Lab 11 - 12/Models/Entities/GoldMine.cs
namespace Projekt_Lab_11___12.Models.Entities
{
    public class GoldMine : Mine
    {
        public GoldMine() {
            Name = "Kopalnia Złota";
            MineResourceType = ResourceType.Gold;
        }
    }
}

Projekt Lab 11 - 12/Models/Entities/IronMine.cs
namespace Projekt_Lab_11___12.Models.Entities
{
    public class IronMine : Mine
    {
        public IronMine() { 
            Name = "Kopalnia Żelaza";
            MineResourceType = ResourceType.Iron;
        }
    }
}

Projekt Lab 11 - 12/Models/Entities/Mine.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Projekt_Lab_11___12.Models.Entities
{
    public abstract class Mine
    {
        [Key]
        public int Id { get; set; }
        public int Level { get; set; } = 1;
        public string Name { get; set; }
        public ResourceType MineResourceType { get; set; }

        [Range(0.01, double.MaxValue, ErrorMessage = "Minimalne wartość to 0,01")]
        public double PermAdditionalValue { get; set; } = 0;

        public BonusClicks BonusClicks { get; set; } = new();

        protected Mine() {
        }
    }
}

Projekt Lab 11 - 12/Models/ViewModels/MineViewModel.cs
using Projekt_Lab_11___12.Models.Entities;

namespace Projekt_Lab_11___12.Models.ViewModels
{
    public class MineViewModel
    {
        public double Iron { get; set; }
        public double Gold { get; set; }
        public double Diamond { get; set; }
        public double Emerald { get; set; }
        public IronMine IronMine { get; set; }
        public GoldMine GoldMine { get; set; }
        public DiamondMine DiamondMine { get; set; }
    }
}

Projekt Lab 11 - 12/Controllers/EquipmentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Projekt_Lab_11___12.Services.Interfaces;

namespace Projekt_Lab_11___12.Controllers
{
    public class EquipmentController : Controller
    {
        private readonly IEquipmentService _equipmentService;
        private readonly ILogger<EquipmentController> _logger;

        public EquipmentController(IEquipmentService equipmentService, ILogger<EquipmentController> logger)
        {
            _equipmentService = equipmentService;
            _logger = logger;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var model = await _equipmentService.EquipmentViewModel();
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Equip(int pickaxeId)
        {
            var (succes, message) = await _equipmentService.Equip(pickaxeId);
            return RedirectToAction(nameof(Index));
        }
    }
}

Projekt Lab 11 - 12/Controllers/MineController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Projekt_Lab_11___12.Models.Entities;
using Projekt_Lab_11___12.Services.Interfaces;

namespace Projekt_Lab_11___12.Controllers
{
    public class MineController : Controller
    {
        private readonly ILogger<MineController> _logger;
        private readonly IMineService _mineService;

        public MineController(
            IMineService mineService,
            ILogger<MineController> logger
            )
        {
            _mineService = mineService;
            _logger = logger;
        }

        [Authorize]
        public async Task<IActionResult> IronMine() {
            var model = await _mineService.MineViewModel();
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> GoldMine()
        {
            var model = await _mineService.MineViewModel();
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> DiamondMine()
        {
            var model = await _mineService.MineViewModel();
            return View(model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PointsForClick([FromBody] ResourceType resourceType)
        {
            var result = await _mineService.PointsForClick(resourceType);

            if (double.TryParse(result, out double points))
            {
                return Json(new { success = true, points = points });
            }
            else
            {
                return Json(new { success = false, message = result });
            }
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BonusPointsForClick([FromBody] ResourceType resourceType)
        {
            var result = await _mineService.BonusPointsForClick(resourceType);

            if (double.TryParse(result, out double points))
            {
                return Json(new { success = true, points = points });
            }
            else
            {
                return Json(new { success = false, message = result });
            }

        }


    }
}

Projekt Lab 11 - 12/Controllers/RankingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Projekt_Lab_11___12.Services.Interfaces;

namespace Projekt_Lab_11___12.Controllers
{
    public class RankingController : Controller
    {
        private readonly IRankingService _rankingService;

        public RankingController(IRankingService rankingService)
        {
            _rankingService = rankingService;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var model = await _rankingService.RankingViewModel();
            return View(model);
        }
    }
}

Projekt Lab 11 - 12/Controllers/StoreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Projekt_Lab_11___12.Services;
using Projekt_Lab_11___12.Services.Interfaces;

namespace Projekt_Lab_11___12.Controllers
{
    public class StoreController : Controller
    {
        private readonly ILogger<MineController> _logger;
        private readonly IStoreService _storeService;

        public StoreController(
            ILogger<MineController> logger, 
            IStoreService storeService
            )
        {
            _logger = logger;
            _storeService = storeService;
        }

        [Authorize]
        public async Task<IActionResult> Index(int page = 1, string searchQuery = "", string sortOrder = "")
        {
            var model = await _storeService.StoreViewModel(page, 3, searchQuery, sortOrder);
            return View(model);
        }


        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Buy(int pickaxeShopId)
        {
            var (success, message) = await _storeService.Buy(pickaxeShopId);
            var model = await _storeService.StoreViewModel();

            if (!success)
            {
                model.PurchaseErrors[pickaxeShopId] = message;
                return View("Index", model);
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [Authorize, HttpPost]
        public async Task<IActionResult> BuyAdditionalRes(int mineId)
        {
            await _storeService.BuyAdditionalRes(mineId);

            return RedirectToAction(nameof(Index));
        }
    }
}

Projekt Lab 11 - 12/Controllers/UpgradeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Projekt_Lab_11___12.Models.Entities;
using Projekt_Lab_11___12.Services;
using Projekt_Lab_11___12.Services.Interfaces;

namespace Projekt_Lab_11___12.Controllers
{
    public class UpgradeController : Controller
    {
        private readonly IUpgradeService _upgradeService;

        public UpgradeController(IUpgradeService upgradeService)
        {
            _upgradeService = upgradeService;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var model = await _upgradeService.UpgradeViewModel();
            return View(model);
        }

        [Authorize, HttpPost]
        public async Task<IActionResult> Upgrade(int upgradeMineId)
        {
            var (success, message) = await _upgradeService.Upgrade(upgradeMineId);
            var model = await _upgradeService.UpgradeViewModel();

            if (!success)
            {
                model.PurchaseErrors[upgradeMineId] = message;
                return View("Index", model);
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [Authorize, HttpPost]
        public async Task<IActionResult> ResetAccount()
        {
            await _upgradeService.ResetAccount();

            return RedirectToAction(nameof(Index));
        }
    }
}

Projekt Lab 11 - 12/Views/Mine/DiamondMine.cshtml
@model Projekt_Lab_11___12.Models.ViewModels.MineViewModel

@{
    ViewData["Title"] = "Kopalnia Diamentów";
}

@section Styles {
    <link rel="stylesheet" href="~/css/mine-site.css" />
}

@Html.AntiForgeryToken()

<div class="mine-container">
    <div class="navbar">
        <a asp-controller="Mine" asp-action="IronMine" class="navbar-link">
            <img src="~/img/iron-mine.png" />
        </a>
        <a asp-controller="Mine" asp-action="GoldMine" class="navbar-link">
            <img src="~/img/gold-mine.png" />
        </a>
        <a asp-controller="Mine" asp-action="DiamondMine" class="navbar-link">
            <img src="~/img/diamond-mine.png" />
        </a>
        <a asp-controller="Store" asp-action="Index" class="navbar-link">
            <img src="~/img/store.png" />
        </a>
        <a asp-controller="Equipment" asp-action="Index" class="navbar-link">
            <img src="~/img/pickaxe/pickaxe-0.png" />
        </a>
        <a asp-controller="Upgrade" asp-action="Index" class="navbar-link">
            <img src="~/img/upgrade.png" />
        </a>
        <a asp-controller="Ranking" asp-action="Index" class="navbar-link">
            <img src="~/img/ranking.png" />
        </a>
        @if (User.IsInRole("Admin"))
        {
            <a asp-controller="Admin" asp-action="Index" class="navbar-link">
                <img src="~/img/admin.png" />
            </a>
        }
        <form asp-area="Identity" asp-page="/Account/Logout" method="post" class="navbar-link">
            <button type="submit">
                <img src="~/img/logout.png" alt="Logout" />
            </button>
        </form>
    </div>

    <div class="content">
        <div class="player-info">
            <div class="resources">
                @if (Model != null)
                {
                    <span id="iron-count">@Model.Iron.ToString("F2", System.Globalization.CultureInfo.InvariantCulture)</span> <img src="~/img/iron.png" />
                    <span id="gold-count">@Model.Gold.ToString("F2", System.Globalization.CultureInfo.InvariantCulture)</span> <img src="~/img/gold.png" />
                    <span id="diamond-count">@Model.Diamond.ToString("F2", System.Globalization.CultureInfo.InvariantCulture)</span> <img src="~/img/diamond.png" />
                    <span id="diamond-count">@Model.Emerald.ToString("F2", System.Globalization.CultureInfo.InvariantCulture)</span> <img src="~/img/emerald.png" />
                }
            </div>
        </div>

        <div id="mine" style="position: relative;">
            <img id="mineclick" src="~/img/mine-1.jpg" style="width: 100%;" />
            <div id="minecart">
                <div class="progress-bar">
                    <div class="progress-fill"
                         data-current="@Model.DiamondMine.BonusClicks.CurrentClicks"
                         data-max="@Model.DiamondMine.BonusClicks.MaxClicks"
                          style="width: @( (int)(((double)Model.DiamondMine.BonusClicks.CurrentClicks / Model.DiamondMine.BonusClicks.MaxClicks) * 100) )%;"></div>
                </div>
                <img id="minecartclick" src="~/img/minecart.png" />
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        let diamondCount = parseFloat(document.getElementById('diamond-count').textContent);

        document.getElementById("mineclick").addEventListener("click", async function (e) {
            const token = document.querySelector('input[name="__RequestVerificationToken"]').value;

            const response = await fetch("/Mine/PointsForClick", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "RequestVerificationToken": token
                },
                body: JSON.stringify(2)
            });

            const result = await response.json();

            const indicator = document.createElement("div");
            indicator.style.position = "absolute";
            indicator.style.left = `${e.offsetX}px`;
            indicator.style.top = `${e.offsetY}px`;
            indicator.style.fontSize = "20px";
            indicator.style.fontWeight = "bold";
            indicator.style.pointerEvents = "none";
            indicator.style.opacity = "1";
            indicator.style.transition = "opacity 1s ease-out";

            if (result.success) {
                indicator.textContent = `+${result.points.toFixed(2)}`;
                indicator.style.color = "DeepSkyBlue";

                diamondCount += result.points;
                document.getElementById('diamond-count').textContent = diamondCount.toFixed(2);
            } else {
                indicator.textContent = result.message;
                indicator.style.color = "red";
            }

            document.getElementById("mine").appendChild(indicator);

            setTimeout(() => {
                indicator.style.opacity = "0";
                setTimeout(() => indicator.remove(), 1000);
            }, 1500);
        });

        
        document.getElementById("minecartclick").addEventListener("click", async function (e) {
            const token = document.querySelector('input[name="__RequestVerificationToken"]').value;
            const progressFill = document.querySelector('.progress-fill');

            const response = await fetch("/Mine/BonusPointsForClick", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "RequestVerificationToken": token
                },
                body: JSON.stringify(2)
            });

            const result = await response.json();

            const indicator = document.createElement("div");
            indicator.style.position = "absolute";
            indicator.style.left = `${e.offsetX}px`;
            indicator.style.top = `${e.offsetY}px`;
            indicator.style.fontSize = "20px";
            indicator.style.fontWeight = "bold";
            indicator.style.pointerEvents = "none";
            indicator.style.opacity = "1";
            indicator.style.transition = "opacity 1s ease-out";

            if (result.success) {
                progressFill.dataset.current -= 1;
                const percent = Math.floor((progressFill.dataset.current / progressFill.dataset.max) * 100);
                progressFill.style.width = percent + '%';

                indicator.textContent = `+${result.points.toFixed(2)}`;
                indicator.style.color = "DeepSkyBlue";

                diamondCount += result.points;
                document.getElementById('diamond-count').textContent = diamondCount.toFixed(2);
            } else {
                indicator.textContent = result.message;
                indicator.style.color = "red";
            }

            document.getElementById("minecart").appendChild(indicator);

            setTimeout(() => {
                indicator.style.opacity = "0";
                setTimeout(() => indicator.remove(), 1000);
            }, 1500);
        });
    </script>
}

Projekt Lab 11 - 12/Views/Mine/GoldMine.cshtml
@model Projekt_Lab_11___12.Models.ViewModels.MineViewModel

@{
    ViewData["Title"] = "Kopalnia Złota";
}

@section Styles {
    <link rel="stylesheet" href="~/css/mine-site.css" />
}

@Html.AntiForgeryToken()

<div class="mine-container">
    <div class="navbar">
        <a asp-controller="Mine" asp-action="IronMine" class="navbar-link">
            <img src="~/img/iron-mine.png" />
        </a>
        <a asp-controller="Mine" asp-action="GoldMine" class="navbar-link">
            <img src="~/img/gold-mine.png" />
        </a>
        <a asp-controller="Mine" asp-action="DiamondMine" class="navbar-link">
            <img src="~/img/diamond-mine.png" />
        </a>
        <a asp-controller="Store" asp-action="Index" class="navbar-link">
            <img src="~/img/store.png" />
        </a>
        <a asp-controller="Equipment" asp-action="Index" class="navbar-link">
            <img src="~/img/pickaxe/pickaxe-0.png" />
        </a>
        <a asp-controller="Upgrade" asp-action="Index" class="navbar-link">
            <img src="~/img/upgrade.png" />
        </a>
        <a asp-controller="Ranking" asp-action="Index" class="navbar-link">
            <img src="~/img/ranking.png" />
        </a>
        @if (User.IsInRole("Admin"))
        {
            <a asp-controller="Admin" asp-action="Index" class="navbar-link">
                <img src="~/img/admin.png" />
            </a>
        }
        <form asp-area="Identity" asp-page="/Account/Logout" method="post" class="navbar-link">
            <button type="submit">
                <img src="~/img/logout.png" alt="Logout" />
            </button>
        </form>
    </div>

    <div class="content">
        <div class="player-info">
            <div class="resources">
                @if (Model != null)
                {
                    <span id="iron-count">@Model.Iron.ToString("F2", System.Globalization.CultureInfo.InvariantCulture)</span> <img src="~/img/iron.png" />
                    <span id="gold-count">@Model.Gold.ToString("F2", System.Globalization.CultureInfo.InvariantCulture)</span> <img src="~/img/gold.png" />
                    <span id="diamond-count">@Model.Diamond.ToString("F2", System.Globalization.CultureInfo.InvariantCulture)</span> <img src="~/img/diamond.png" />
                    <span id="diamond-count">@Model.Emerald.ToString("F2", System.Globalization.CultureInfo.InvariantCulture)</span> <img src="~/img/emerald.png" />
                }
            </div>
        </div>

        <div id="mine" style="position: relative;">
            <img id="mineclick" src="~/img/mine-1.jpg" style="width: 100%;" />
            <div id="minecart">
                <div class="progress-bar">
                   <div class="progress-fill"
                         data-current="@Model.GoldMine.BonusClicks.CurrentClicks"
                         data-max="@Model.GoldMine.BonusClicks.MaxClicks"
                         style="width: @( (int)(((double)Model.GoldMine.BonusClicks.CurrentClicks / Model.GoldMine.BonusClicks.MaxClicks) * 100) )%;"></div>
                </div>
                <img id="minecartclick" src="~/img/minecart.png" />
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        let goldCount = parseFloat(document.getElementById('gold-count').textContent);

        document.getElementById("mineclick").addEventListener("click", async function (e) {
            const token = document.querySelector('input[name="__RequestVerificationToken"]').value;

            const response = await fetch("/Mine/PointsForClick", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "RequestVerificationToken": token
                },
                body: JSON.stringify(1)
            });

            const result = await response.json();

            const indicator = document.createElement("div");
            indicator.style.position = "absolute";
            indicator.style.left = `${e.offsetX}px`;
            indicator.style.top = `${e.offsetY}px`;
            indicator.style.fontSize = "20px";
            indicator.style.fontWeight = "bold";
            indicator.style.pointerEvents = "none";
            indicator.style.opacity = "1";
            indicator.style.transition = "opacity 1s ease-out";

            if (result.success) {
                indicator.textContent = `+${result.points.toFixed(2)}`;
                indicator.style.color = "gold";

                goldCount += result.points;
                document.getElementById('gold-count').textContent = goldCount.toFixed(2);
            } else {
                indicator.textContent = result.message;
                indicator.style.color = "red";
            }

            document.getElementById("mine").appendChild(indicator);

            setTimeout(() => {
                indicator.style.opacity = "0";
                setTimeout(() => indicator.remove(), 1000);
            }, 1500);
        });

        document.getElementById("minecartclick").addEventListener("click", async function (e) {
            const token = document.querySelector('input[name="__RequestVerificationToken"]').value;
            const progressFill = document.querySelector('.progress-fill');

            const response = await fetch("/Mine/BonusPointsForClick", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "RequestVerificationToken": token
                },
                body: JSON.stringify(1)
            });

            const result = await response.json();

            const indicator = document.createElement("div");
            indicator.style.position = "absolute";
            indicator.style.left = `${e.offsetX}px`;
            indicator.style.top = `${e.offsetY}px`;
            indicator.style.fontSize = "20px";
            indicator.style.fontWeight = "bold";
            indicator.style.pointerEvents = "none";
            indicator.style.opacity = "1";
            indicator.style.transition = "opacity 1s ease-out";

            if (result.success) {
                progressFill.dataset.current -= 1;
                const percent = Math.floor((progressFill.dataset.current / progressFill.dataset.max) * 100);
                progressFill.style.width = percent + '%';

                indicator.textContent = `+${result.points.toFixed(2)}`;
                indicator.style.color = "gold";

                goldCount += result.points;
                document.getElementById('gold-count').textContent = goldCount.toFixed(2);
            } else {
                indicator.textContent = result.message;
                indicator.style.color = "red";
            }

            document.getElementById("minecart").appendChild(indicator);

            setTimeout(() => {
                indicator.style.opacity = "0";
                setTimeout(() => indicator.remove(), 1000);
            }, 1500);
        });
    </script>
}

Projekt Lab 11 - 12/Views/Mine/IronMine.cshtml
@model Projekt_Lab_11___12.Models.ViewModels.MineViewModel

@{
    ViewData["Title"] = "Kopalnia Żelaza";
}

@section Styles {
    <link rel="stylesheet" href="~/css/mine-site.css" />
}

@Html.AntiForgeryToken()

<div class="mine-container">
    <div class="navbar">
        <a asp-controller="Mine" asp-action="IronMine" class="navbar-link">
            <img src="~/img/iron-mine.png" />
        </a>
        <a asp-controller="Mine" asp-action="GoldMine" class="navbar-link">
            <img src="~/img/gold-mine.png" />
        </a>
        <a asp-controller="Mine" asp-action="DiamondMine" class="navbar-link">
            <img src="~/img/diamond-mine.png" />
        </a>
        <a asp-controller="Store" asp-action="Index" class="navbar-link">
            <img src="~/img/store.png" />
        </a>
        <a asp-controller="Equipment" asp-action="Index" class="navbar-link">
            <img src="~/img/pickaxe/pickaxe-0.png" />
        </a>
        <a asp-controller="Upgrade" asp-action="Index" class="navbar-link">
            <img src="~/img/upgrade.png" />
        </a>
        <a asp-controller="Ranking" asp-action="Index" class="navbar-link">
            <img src="~/img/ranking.png" />
        </a>
        @if (User.IsInRole("Admin"))
        {
            <a asp-controller="Admin" asp-action="Index" class="navbar-link">
                <img src="~/img/admin.png" />
            </a>
        }
        <form asp-area="Identity" asp-page="/Account/Logout" method="post" class="navbar-link">
            <button type="submit">
                <img src="~/img/logout.png" alt="Logout" />
            </button>
        </form>



    </div>

    <div class="content">
        <div class="player-info">
            <div class="resources">
                @if (Model != null)
                {
                    <span id="iron-count">@Model.Iron.ToString("F2", System.Globalization.CultureInfo.InvariantCulture)</span> <img src="~/img/iron.png" />
                    <span id="gold-count">@Model.Gold.ToString("F2", System.Globalization.CultureInfo.InvariantCulture)</span> <img src="~/img/gold.png" />
                    <span id="diamond-count">@Model.Diamond.ToString("F2", System.Globalization.CultureInfo.InvariantCulture)</span> <img src="~/img/diamond.png" />
                    <span id="diamond-count">@Model.Emerald.ToString("F2", System.Globalization.CultureInfo.InvariantCulture)</span> <img src="~/img/emerald.png" />
                }
            </div>
        </div>

        <div id="mine" style="position: relative;">
            <img id="mineclick" src="~/img/mine-1.jpg" style="width: 100%;" />
            <div id="minecart">
                <div class="progress-bar">
                    <div class="progress-fill"
                         data-current="@Model.IronMine.BonusClicks.CurrentClicks"
                         data-max="@Model.IronMine.BonusClicks.MaxClicks"
                         style="width: @( (int)(((double)Model.IronMine.BonusClicks.CurrentClicks / Model.IronMine.BonusClicks.MaxClicks) * 100) )%;"></div>
                </div>
                <img id="minecartclick" src="~/img/minecart.png" />
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        let ironCount = parseFloat(document.getElementById('iron-count').textContent);

        document.getElementById("mineclick").addEventListener("click", async function (e) {
            const token = document.querySelector('input[name="__RequestVerificationToken"]').value;

            const response = await fetch("/Mine/PointsForClick", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "RequestVerificationToken": token
                },
                body: JSON.stringify(0)
            });

            const result = await response.json();

            const indicator = document.createElement("div");
            indicator.style.position = "absolute";
            indicator.style.left = `${e.offsetX}px`;
            indicator.style.top = `${e.offsetY}px`;
            indicator.style.fontSize = "20px";
            indicator.style.fontWeight = "bold";
            indicator.style.pointerEvents = "none";
            indicator.style.opacity = "1";
            indicator.style.transition = "opacity 1s ease-out";

            if (result.success) {
                indicator.textContent = `+${result.points.toFixed(2)}`;
                indicator.style.color = "white";

                ironCount += result.points;
                document.getElementById('iron-count').textContent = ironCount.toFixed(2);
            } else {
                indicator.textContent = result.message;
                indicator.style.color = "red";
            }

            document.getElementById("mine").appendChild(indicator);

            setTimeout(() => {
                indicator.style.opacity = "0";
                setTimeout(() => indicator.remove(), 1000);
            }, 1500);
        });


        document.getElementById("minecartclick").addEventListener("click", async function (e) {
            const token = document.querySelector('input[name="__RequestVerificationToken"]').value;
            const progressFill = document.querySelector('.progress-fill');

            const response = await fetch("/Mine/BonusPointsForClick", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "RequestVerificationToken": token
                },
                body: JSON.stringify(0)
            });

            const result = await response.json();

            const indicator = document.createElement("div");
            indicator.style.position = "absolute";
            indicator.style.left = `${e.offsetX}px`;
            indicator.style.top = `${e.offsetY}px`;
            indicator.style.fontSize = "20px";
            indicator.style.fontWeight = "bold";
            indicator.style.pointerEvents = "none";
            indicator.style.opacity = "1";
            indicator.style.transition = "opacity 1s ease-out";

            if (result.success) {
                progressFill.dataset.current -= 1;
                const percent = Math.floor((progressFill.dataset.current / progressFill.dataset.max) * 100);
                progressFill.style.width = percent + '%';

                indicator.textContent = `+${result.points.toFixed(2)}`;
                indicator.style.color = "white";

                ironCount += result.points;
                document.getElementById('iron-count').textContent = ironCount.toFixed(2);
            } else {
                indicator.textContent = result.message;
                indicator.style.color = "red";
            }

            document.getElementById("minecart").appendChild(indicator);

            setTimeout(() => {
                indicator.style.opacity = "0";
                setTimeout(() => indicator.remove(), 1000);
            }, 1500);
        });

    </script>
}